test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

#
# Cloud Storage Keys (Edited Using -> rails credentials:edit)
#

# Handles Digital Ocean Credentials
digitalocean:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:digitalocean, :access_key) %>
  secret_access_key: <%= Rails.application.credentials.dig(:digitalocean, :secret) %>
  region: <%= Rails.application.credentials.dig(:digitalocean, :region) %>
  bucket: <%= Rails.application.credentials.dig(:digitalocean, :bucket) %>
  endpoint: <%= Rails.application.credentials.dig(:digitalocean, :endpoint) %>
  force_path_style: true
