test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

#
# Cloud Storage Keys (Edited Using -> rails credentials:edit)
#

# Handles Digital Ocean Credentials
digitalocean:
  service: S3
  endpoint: https://heat-images.nyc3.digitaloceanspaces.com
  access_key_id: <%= Rails.application.credentials.dig(:digitalocean, :access_key) %>
  secret_access_key: <%= Rails.application.credentials.dig(:digitalocean, :secret) %>
  bucket: your-space-name-here
  region: unused
