test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

#
# Cloud Storage Keys (Edited Using -> rails credentials:edit)
#

# Handles Digital Ocean Credentials
digitalocean:
  service: S3
  access_key_id: <%= ENV['DIGITAL_OCEAN_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['DIGITAL_OCEAN_SECRET'] %>
  region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
  bucket: <%= ENV['DIGITAL_OCEAN_BUCKET'] %>
  endpoint: <%= ENV['DIGITAL_OCEAN_ENDPOINT'] %>
  force_path_style: true
